services:
  cache:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - cache:/data
volumes:
  cache:
    driver: local
